title: Welcome to my GitHub Pages sample site
author: Thinh Pham
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! This is a sample GitHub Pages site. More interesting content to come.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
